_parent_: configs/base.yaml

tb: false
batch_size: 1                                               
load: 

nerf:
    rand_rays_test: 20480                                     # number of random rays for each step

data_test:
    dtu:
        root_dir: /your_data_path/DTU
        dataset_name: dtu                                    
        img_wh: [640, 512]                                 
        num_workers: 4                                        
        max_len: -1
        test_views_method: nearest
    llff:
        root_dir: /your_data_path/llff
        dataset_name: llff                                      
        img_wh: [960, 640]                                  
        num_workers: 4                                       
        max_len: -1
        scene_list:
        test_views_method: nearest
